apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: grupo-9
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: pspd/auth:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50051
          name: grpc
        - containerPort: 8000
          name: metrics
        envFrom:
        - secretRef:
            name: pspd-db
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: grupo-9
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: grpc
    port: 50051
    targetPort: grpc
  - name: metrics
    port: 8000
    targetPort: metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: grupo-9
  labels:
    app: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data
        image: pspd/data:0.1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50052
          name: grpc
        - containerPort: 8000
          name: metrics
        envFrom:
        - secretRef:
            name: pspd-db
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: grupo-9
  labels:
    app: data-service
spec:
  selector:
    app: data-service
  ports:
  - name: grpc
    port: 50052
    targetPort: grpc
  - name: metrics
    port: 8000
    targetPort: metrics
