apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mock-hpa
  namespace: grupo-9
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mock-hospital-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50