apiVersion: v1
kind: Secret
metadata:
  name: pspd-db
  namespace: grupo-9
type: Opaque
stringData:
  DB_HOST: "192.168.122.1"
  DB_PORT: "5432"
  DB_NAME: "pseudopep_g09"
  DB_USER: "<preencher-fora-do-git>"
  DB_PASSWORD: "<preencher-fora-do-git>"
