prometheus:
  prometheusSpec:
    enableRemoteWriteReceiver: true
    retention: 12h
    resources:
      requests:
        memory: "400Mi"
        cpu: "200m"
      limits:
        memory: "800Mi"
        cpu: "500m"